### ISSUE TITLE
Wrong root for lower level domains

### ISSUE THREAD

**Issue by bizm** [calebdoxsey/kubernetes-cloudflare-sync#10]
It fails if "root" is third level domain, e.g.: "example.co.uk". In that case it is trying to get zone id by name "co.uk" instead of "example.co.uk". I had to change this line https://github.com/calebdoxsey/kubernetes-cloudflare-sync/blob/master/main.go#L182 to 
```
for strings.Count(root, ".") > 2 {
```
to make it work for me, but surely you guys can find a proper fix.

**Comment by calebdoxsey** [comment]
@bizm I think I have a fix here https://github.com/calebdoxsey/kubernetes-cloudflare-sync/pull/11.

I pushed a tag to `quay.io/calebdoxsey/kubernetes-cloudflare-sync:zoneIDs` if you want to try it.

**Comment by bizm** [comment]
@calebdoxsey Works like a charm!
