### ISSUE TITLE
ExternalIP list empty on an amazon cluster

### ISSUE THREAD

**Issue by ilkerc** [calebdoxsey/kubernetes-cloudflare-sync#13]
What could be the reason to not detect external ips on this cluster? 
Only internalIP's are available, and public ip list is empty for a cluster I created using aws.
Any workaround for aws?

**Comment by calebdoxsey** [comment]
@ilkerc I'm not currently using amazon EKS, so I'm not sure what might be causing the issue. Perhaps the nodes in your cluster don't have a public IP address?

**Comment by ilkerc** [comment]
Hi @calebdoxsey, thanks for checking out the issue.
Nodes do have public IP addresses, I used to add the A records manually. I'm using rancher UI for the management and decided to also use their api to fetch the external addresses.
