### ISSUE TITLE
Getting error "failed to sync failed to find zone id for dns-name:=kubernetes: error from makeRequest: HTTP status 400:"

### ISSUE THREAD

**Issue by ghost** [calebdoxsey/kubernetes-cloudflare-sync#14]
Hi,

I configured kubernetes-cloudflare-sync and I am recieving this error when launching the pod. Can you please help me to figure this out?

2019/09/01 16:43:47 failed to sync failed to find zone id for dns-name:=kubernetes: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":6003,\"message\":\"Invalid request headers\",\"error_chain\":[{\"code\":6102,\"message\":\"Invalid format for X-Auth-Email header\"},{\"code\":6103,\"message\":\"Invalid format for X-Auth-Key header\"}]}],\"messages\":[],\"result\":null}"

Thanks!

**Comment by calebdoxsey** [comment]
I think you auth key is wrong. It expects them to be sent via environment variables:

```
	CloudflareAPIEmail: os.Getenv("CF_API_EMAIL"),
	CloudflareAPIKey:   os.Getenv("CF_API_KEY"),
```

**Comment by hellovietduc** [comment]
I use the `deployment.yml` file you provide, the `cloudflare` secret was created correctly. Still get the same error as @nitincypher 
```
failed to sync failed to find zone id for dns-name:=hello-world.example.tk: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":6003,\"message\":\"Invalid request headers\",\"error_chain\":[{\"code\":6103,\"message\":\"Invalid format for X-Auth-Key header\"}]}],\"messages\":[],\"result\":null}"
```

**Comment by ghost** [comment]
@vietduc01100001  I ended up getting static ip and configured kubeip. Works seamlessly for me.

**Comment by hellovietduc** [comment]
> @vietduc01100001 I ended up getting static ip and configured kubeip. Works seamlessly for me.

I figured it out. I was using an access token instead of a global API key. Now my configuration works seamlessly too. :)

**Comment by ghost** [comment]
@vietduc01100001 Oh, I got it now. :) Thanks anyways...
