### ISSUE TITLE
Publish to Docker Hub?

### ISSUE THREAD

**Issue by kieranajp** [calebdoxsey/kubernetes-cloudflare-sync#2]
Hey Caleb,

First, thanks for the amazing tutorial and for this repo. I was trying last night to come up with a K8s implementation that [works on php-fpm](https://github.com/kieranajp/k8s-php-fpm) and your blog post was invaluable.

That said, it would be really useful if you could publish this particular repo's container to Docker Hub or similar? Is that something you would be happy to do?

Cheers,
--Kieran

**Comment by hbagdi** [comment]
+1 @calebdoxsey

**Comment by calebdoxsey** [comment]
@kieranajp @hbagdi its now available on dockerhub: https://hub.docker.com/r/calebdoxsey/kubernetes-cloudflare-sync/

Thanks.

**Comment by kieranajp** [comment]
Amazing, thank you @calebdoxsey!

**Comment by hbagdi** [comment]
Thanks!
