### ISSUE TITLE
Question: difference with external-dns

### ISSUE THREAD

**Issue by ii64** [calebdoxsey/kubernetes-cloudflare-sync#20]
I wonder if there's any differences with https://github.com/kubernetes-sigs/external-dns
Thanks!

**Comment by calebdoxsey** [comment]
Yes @ii64 you should probably use that package. This project was intended to be more of an example than something you'd run in production.

That said it looks like External DNS syncs records for services and ingresses? This application syncs the node IPs circumventing the need for a load balancer. (which in general is not how Kubernetes is intended to be used)
