### ISSUE TITLE
Resync operation more frequent than expected

### ISSUE THREAD

**Issue by edahlseng** [calebdoxsey/kubernetes-cloudflare-sync#6]
Thank you for this project (and the associated blog post)! It's been very helpful as I get up to speed with Kubernetes.

I recently deployed this project to a Kubernetes cluster, but upon viewing the logs noticed that the `UpdateFunc` is being called every 2-5 seconds, even though the shared informer factory is configured with a resync period of `time.Minute`. Do you know why this is happening? I'm still learning with Kubernetes and I haven't been able to figure out what the cause for this is.

**Comment by calebdoxsey** [comment]
Hi @edahlseng 

I've also noticed this, which is why I put into the de-bounce cache. I think it might have to do with a property on the node changing: https://github.com/kubernetes/kubernetes/issues/44879. So I guess its working as designed.

**Comment by edahlseng** [comment]
Ah, interesting! Thanks for linking to that issue. Makes sense now!
